### ISSUE TITLE
Problem when use UUID in $filter

### ISSUE THREAD

**Issue by AntonIV8** [SAP/olingo-jpa-processor-v4#136]
Hello. I have problem, when try run GET request with 

$filter=SomeUUIDField eq 53513849-4d3c-4060-9231-2f83dfa14bda

**Response**

"error": {
       "code": null,
       "message": "java.util.UUID.<init>(java.lang.String)"
 }
 
**This is how I describe model field:**

_@Converter(converterClass = UUIDConverter.class, name = "SomeUUIDField")
@Convert("SomeUUIDField")
@Column(name = "SomeUUIDField", length = 36, unique = true, nullable = false)
private UUID SomeUUIDField;_

**Converter class from tutorials:**

    public class UUIDConverter implements org.eclipse.persistence.mappings.converters.Converter {
    private static final long serialVersionUID = 1L;

    Override
    public UUID convertObjectValueToDataValue(Object objectValue, Session session) {
        return (UUID) objectValue;
    }

    @Override
    public UUID convertDataValueToObjectValue(Object dataValue, Session session) {
        return (UUID) dataValue;
    }

    @Override
    public boolean isMutable() {
        return false;
    }

    @Override
    public void initialize(DatabaseMapping mapping, Session session) {
        DatabaseField field = mapping.getField();
        field.setSqlType(Types.LONGNVARCHAR);
        field.setTypeName("java.util.UUID");
        field.setColumnDefinition("UUID");
    }
    }

**Comment by wog48** [comment]
Hello,

I had a look at the issue. The solution is part of https://github.com/SAP/olingo-jpa-processor-v4/pull/137. Pleas have a look at [JPALiteralOperator](https://github.com/SAP/olingo-jpa-processor-v4/pull/137/files?authenticity_token=x2ABi7pnYZ%2FdfHp0PSsmJbSwKwYeHcPFnG688SDSSwKqDXIvk4tJX%2F0dp3%2Btr00xYC0ojD1Iy2pHY3LjkJl1rA%3D%3D&file-filters%5B%5D=.java&file-filters%5B%5D=.xml#diff-0790a73f257f0298aa8efba15f299322e277680d42f82aa8e04bc3068652ed45) adoption
