### ISSUE TITLE
Can we use JAX-RS server with your code?

### ISSUE THREAD

**Issue by ericraskin** [SAP/olingo-jpa-processor-v4#14]
Hi:

Rather than just using a plain servlet, can we use the full Apache CXF stack - specifically JAX-RS and the OAuth2 server implementation?

I am not expert in all of this, so any advice would be much appreciated.

If it matters, our base application is working fine based on your code and the tutorial.  Thanks for the great work!

   Eric Raskin

**Comment by wog48** [comment]
I don't have any real experience with Apache CXF. I only used it when I implemented an Olingo based OData V2 service. 

Just by looking at the code of Olingo V2 I feel confidence that a developer with more knowledge about Apache CXF can create something similar like org.apache.olingo.odata2.core.rest and use the JPA Processor there. 

For my understanding Olingo went away from Apache CXF to give the user of the framework more freedom to use it together with different frameworks like  Apache CXF or Spring or to use it with a plain servlet.

Oliver

**Comment by ericraskin** [comment]
I actually managed to get it to work.  The trick was in how I had to configure the @Path and Address settings so that JAX RS URL mapping wouldn't interfere with the way Olingo pulled out the OData request from the URL.  Now that I have this working, I can add OAuth 2.0 if the client wants it.  Yet another adventure...
