### ISSUE TITLE
$count function is not working with with MS SQL server

### ISSUE THREAD

**Issue by kumar842** [SAP/olingo-jpa-processor-v4#145]
**API** 
http://localhost:8091/v1/Orders/$count
http://localhost:8091/v1/Orders?$count=true

**Error:**
`{
    "error": {
        "code": null,
        "message": "class java.lang.Integer cannot be cast to class java.lang.Long"
    }
}`

In MS SQL server, the return type of the count function is int. 
![Annotation 2022-02-21 200426](https://user-images.githubusercontent.com/7290973/155265814-e4f5ddb3-6230-488a-8f2d-26a6a95c7c64.png)

JPAJoinQuery.java > CountResults() method will be called in case of /orders/$count or /orders?$count=true. 
This calls getSingleResult() (line no: 104). So, expected return type is Long.

![Annotation 2022-02-21 141828](https://user-images.githubusercontent.com/7290973/155265698-4f90985f-f6ff-4548-bbd3-d469de02d48b.png)

TypeQueryImpl.java >  getSingleResult() calls getResultList()(line no: 185), which returns List<Integer> instead of List<Long)

![Annotation 2022-02-21 143514](https://user-images.githubusercontent.com/7290973/155265607-0163880c-2e99-4ee1-9cca-351b9f70069e.png)

because the select count() query returns List<Integer>.
![Annotation 2022-02-21 142036](https://user-images.githubusercontent.com/7290973/155265797-96429a1d-405f-42fa-9815-4d6e959d6378.png)

Can you please help or guide here.

**Comment by wog48** [comment]
Hello,


I have create a new version containing a correction. 

At the end it was surprising that a an Integer is returned even so the corresponding `CriteriaBuilder`  method indicates that count returns a Long: `Expression<Long> countDistinct(Expression<?> x);`

In case you still face a problem, reopen the issue.
