### ISSUE TITLE
POSTing new entity with @ManyToOne relation failing

### ISSUE THREAD

**Issue by ajheflin** [SAP/olingo-jpa-processor-v4#146]
Attached is a screenshot of the request being made to the endpoint:
![image](https://user-images.githubusercontent.com/77823405/155392821-134e72ae-99a6-4a1e-9091-52f6c10dbdef.png)

And the error being returned is
`Cannot insert the value NULL into column 'issue_id', table 'db.logs'; column does not allow nulls. INSERT fails`

The database name has been obscured for privacy reasons but the database is MS SQL.

The entity class for Log is as follows: 
![image](https://user-images.githubusercontent.com/77823405/155393348-2bb54435-917d-4790-91c4-66c8561fcb9e.png)

It's worth noting that created, createdBy, modified, and modifiedBy are all values that are calculated as the object is being persisted, and do not need to be posted with the request body.

**Comment by wog48** [comment]
Two questions:

- Which version do you use?
- Do you use JPAExampleCUDRequestHandler as CUDRequestHandler?

**Comment by ajheflin** [comment]
I cloned the latest. My pom.xml says 1.0.6. 

I ended up resolving it by creating a custom implementation of the CUDRequestHandler, but originally I was using the default one, yes. I'm mostly just curious if the error originally was something on my end or an issue with the framework. I had also tried creating an IDClass that implemented Serializable but no dice there, either.

**Comment by wog48** [comment]
The idea of `JPAExampleCUDRequestHandler` is to support you in rapid prototyping, it may not be able to handle all situations. As the ìmplementation of `JPACUDRequestHandler` is the place to implement business logic the JPA Processor can only provide some supporting functions.
