### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by chentopf** [SAP/olingo-jpa-processor-v4#15]
Hi,
Is there a way to do automatic pagination on the server in case the number of retrieved data is to big?

Thanks... 
Chen

**Comment by wog48** [comment]
Unfortunately as of now server-driven paging, as described in  [section 11.2.5.7](https://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part1-protocol/odata-v4.0-errata03-os-part1-protocol-complete.html#_Toc453752288), is not supported, only client side via $top and $skip.

**Comment by wog48** [comment]
In the meantime server driven paging on the top level entity is supported
