### ISSUE TITLE
Invalid argument resultSetType, use TYPE_FORWARD_ONLY

### ISSUE THREAD

**Issue by dinesh103201** [SAP/olingo-jpa-processor-v4#152]
In java project we are connecting to HANA db through eclipse link JPA. And getting below exception when trying to fetch data.

> com.sap.db.jdbc.exceptions.SQLDataExceptionSapDB: Invalid argument resultSetType, use TYPE_FORWARD_ONLY.

In eclipseLink JPA, how to enable the feature for scroll forward and backward.

ngdbc driver jar version - 2.13.9
org.eclipse.persistence.jpa jar version - 2.7.10

**Comment by wog48** [comment]
Hello,

I set up my test service connected to a HANA. I'm using the following Versions:

HANA: 2.00.054.00.1611906357
com.sap.cloud.db.jdbc: 2.13.5
org.eclipse.persistence.jpa: 2.13.5

Executing my standard tests I did not get an error. SO could you please provide some more detaile about the request and the metadata of your service?

Best Regards

**Comment by wog48** [comment]
No responce for some time. The issue gets closed. In case you still face the problem, reopen the issue.
