### ISSUE TITLE
Maven compiler plugin needed for Maven >= 3

### ISSUE THREAD

**Issue by Boltzmann** [SAP/olingo-jpa-processor-v4#160]
When following the quickstart I get a similar warning from Maven than mentioned on e.g. [stackoverflow](https://stackoverflow.com/questions/4123044/maven-3-warnings-about-build-plugins-plugin-version) at step 

> Open a shell, like the Windows console, navigate to the directory the repository had been cloned to and then to odata-jpa-archetype-spring. Starting from the home directory this could be e.g. `cd git\olingo-jpa-processor-v4\jpa-archetype\odata-jpa-archetype-spring`. We do that to generate the archetype. This is done by execute `mvn clean install archetype:update-local-catalog`. Alternatively you can also use your IDE:

The warning reads
> [WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.sap.olingo:odata-jpa-archetype-spring:jar:1.0.8
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 22, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 

The latest `<version>3.10.1</version>` seems to be fine.

**Comment by wog48** [comment]
I have approved the PR. Please merge it.

**Comment by Boltzmann** [comment]
I cannot merge it, because the sonar build gives me the error

> Error:  Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar (default-cli) on project odata-jpa: Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator -> [Help 1]

What are the details here?

**Comment by wog48** [comment]
PR was merged. Maven versions had been updated.
