### ISSUE TITLE
Type cast error: Can't convert 'class java.math.BigInteger' to 'class java.lang.Long'

### ISSUE THREAD

**Issue by alvachien** [SAP/olingo-jpa-processor-v4#171]
Create a very simply model class:
```java
@Entity
@Table(name = "book_ctgy_def")
public class BookCategory {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) 
    @Column(name = "id")
    private Long id;

...
}
```
The database column created as 
```sql
id bigint,
```

Access it via `http://[localhost:9010/apis/v1/BookCategories`, the error thrown:
```json
{"error":{"code":null,"message":"Type cast error: Can't convert 'class java.math.BigInteger' to 'class java.lang.Long'. @Convert required"}}
```

The same model works with Olingo itself without 'olingo-jpa-processor-v4'.

**Comment by wog48** [comment]
The [TypeConverter](https://github.com/SAP/olingo-jpa-processor-v4/blob/master/jpa/odata-jpa-processor-cb/src/main/java/com/sap/olingo/jpa/processor/cb/impl/TypeConverter.java) currently not supporting this conversion.
I like to point out that it is usually it is risky to map a data type that can take lager number than the data type it shall be mappped to.

**Comment by wog48** [comment]
Additional mappings have been added to TypeConverter
