### ISSUE TITLE
Is it even possible to do server side paging towards the database if ordering can not be guaranteed?

### ISSUE THREAD

**Issue by PerArneng** [SAP/olingo-jpa-processor-v4#191]
The example paging provider in the source repository does an offset/limit query on each page. According to ex the PostgreSQL documentation it's not recommended to do that without an order by. https://www.postgresql.org/docs/current/queries-limit.html . Is it even possible to make reliable server-side paging when the order is not guaranteed?

**Comment by PerArneng** [comment]
One solution that seems to work is to have database views that contain order by to ensure that there is an order

**Comment by wog48** [comment]
Actually, also server driven paging shall by default create an ORDER BY primary key, as it is done for client driven paging with $top and $skip. This is a bug.

**Comment by wog48** [comment]
I have created a correction. See PR https://github.com/SAP/olingo-jpa-processor-v4/pull/194.

Please try it out. In case you still face a problem, reopen the issue
