### ISSUE TITLE
Jakarta persistence & Spring Boot 3 support?

### ISSUE THREAD

**Issue by ozzioma** [SAP/olingo-jpa-processor-v4#195]
Tried setting up an OData service in Spring Boot 3.
The new jakarta.persistence namespace classes are not compatible with the former JPA 2 classes.
Any plans to support Spring Boot 3 & migrate to jakarta.persistence ?

**Comment by wog48** [comment]
There plans to support Jakarta and Spring Boot 3 together with Java 17, but there is no concrete time line.
