### ISSUE TITLE
Query Timing Out

### ISSUE THREAD

**Issue by kishanp519** [SAP/olingo-jpa-processor-v4#196]
The table is pretty large and when a query is being executed, it times out and prints out nothing. Is there a way to print an error when it exceeds the timeout, or adjust it?

```
Jan 23, 2023 @ 10:39:11.082 | 2023-01-23 15:39:11.081 ERROR 12907 --- [nio-4001-exec-2] o.h.engine.jdbc.spi.SqlExceptionHelper   : HikariPool-1 - Connection is not available, request timed out after 30001ms.
-- | --

  | Jan 23, 2023 @ 10:39:11.081 | 2023-01-23 15:39:11.081  WARN 12907 --- [nio-4001-exec-2] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: null

  | Jan 23, 2023 @ 10:38:52.759 | 2023-01-23 15:38:52.759 DEBUG 12907 --- [nnection-reaper] com.amazonaws.internal.SdkSSLSocket      : closing ssm.us-east-1.amazonaws.com/**********
```

**Comment by wog48** [comment]
Can you provide more details?
- Can you provide the URL, at least in an abstract way? 
- How many entries does the table contains?
- maybe you can also provide the generated SQL from a log?

**Comment by kishanp519** [comment]
Error being thrown: `"org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection"`

URL Endpoint is `/User` and along with that my log shows `Query completed with an execution time of 30166 `ms.` This only happens when the query execution time is over 30000. Right before this I ran the exact query 4-5 times and it worked perfectly. This just happens over 30,000 ms.



```
Feb 1, 2023 @ 10:28:49.374 | 2023-02-01 15:28:49.374  INFO 122 --- [io-4000-exec-18] i.StatisticalLoggingSessionEventListener : Session Metrics {
-- | --

  | Feb 1, 2023 @ 10:28:49.366 | 2023-02-01 15:28:49.365 ERROR 122 --- [io-4000-exec-18] o.h.engine.jdbc.spi.SqlExceptionHelper   : HikariPool-1 - Connection is not available, request timed out after 30001ms.

  | Feb 1, 2023 @ 10:28:49.365 | 2023-02-01 15:28:49.365  WARN 122 --- [io-4000-exec-18] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: null
```


There are 77 entries in the table.

**Comment by kishanp519** [comment]
Made adjustments on my end, fixed. Sorry for the issue.
