### ISSUE TITLE
why there is a limitation regarding the number of $filter

### ISSUE THREAD

**Issue by chentopf** [SAP/olingo-jpa-processor-v4#20]
The jar consists with a limitation that allows only one $filter.
Is there a way to change this limitation in the next version?
and allow request like this:
odata/v1/Projects?$filter=Id eq 1 &$filter=Name eq 'foo'

I know you can do it like this:
odata/v1/Projects?$filter=Id eq 1  and Name eq 'foo'

but our filter can be quiet complex, and it will be helpful to pass more than one filter

**Comment by wog48** [comment]
Hello,
what you get is an UriParserSyntaxException, which is thrown from Olingo org.apache.olingo.server.core.uri.parser.Parser. I assume the already the [OData URI syntax](http://docs.oasis-open.org/odata/odata/v4.0/os/abnf/odata-abnf-construction-rules.txt) does not allow the same query option multiple times.

**Comment by wog48** [comment]
Due to clean-up action. All issues created before 2022 get closed.
