### ISSUE TITLE
Not able to filter on entity basis.

### ISSUE THREAD

**Issue by keshavsahu10** [SAP/olingo-jpa-processor-v4#213]
Hi,
I am not able to filter on entity basis whereas i am able to retreive primitive attribute basis for **ne null**.
Eg.   A entity and B entity are related to eachother on OneToOne mapping, when i fire below query
Query :  odata/**A**?$filter=**B** ne null , i am getting below error
"error": {
        "code": null,
        "message": "Index 0 out of bounds for length 0"
    }
Same query work on id(primitive attribute basis)
Query :  odata/**A**?$filter=**B_id** ne null

**Comment by wog48** [comment]
The issue should be solved with version 1.1.1.
In case the problem still exists, reopen the issue
