### ISSUE TITLE
NPE during the NavigationProperties build

### ISSUE THREAD

**Issue by Valeri-Velev** [SAP/olingo-jpa-processor-v4#214]
I did the same as this example https://github.wdf.sap.corp/odata-jpa/odata-v4-jpa-spring-example but now when I try to reach my metadata I receive only this:

{
    "@odata.context": "$metadata",
    "value": []
}

Could you help me?

Best Regards,
Valeri

**Comment by Valeri-Velev** [comment]
Update:

Currently, only enum classes are visible in the response

**Comment by Valeri-Velev** [comment]
Update #2: 

when I call this '/v1' endpoint which should show all my entities I get a response this exception
with status code 500
_{
    "error": {
        "code": null,
        "message": "Cannot invoke \"javax.persistence.OneToOne.mappedBy()\" because the return value of \"java.lang.reflect.AnnotatedElement.getAnnotation(java.lang.Class)\" is null"
    }
}_

And this happens only on the 1st invocation. Every other try to call the endpoint returns this.
_{
    "@odata.context": "$metadata",
    "value": []
}_

After some investigation, I found an NPE in the code. You can see it on the attached screenshot.
<img width="1728" alt="Screenshot 2023-07-13 at 13 41 42" src="https://github.com/SAP/olingo-jpa-processor-v4/assets/36297088/960c530e-9399-45b3-84b1-2a9f32612495">

This is the object for which the error occurs:

@Entity
@Table(name = "edges")
public class WorkflowEdge {

  @Id
  @ManyToOne
  @JoinColumn(name = "id")
  private Workflow workflow;

  @Id
  @JoinColumn(name = "source")
  private Workflow sourceWorkflow;

  @Id
  @JoinColumn(name = "target")
  private Workflow targetWorkflow;
  
  
Best Regards,
Valeri

**Comment by wog48** [comment]
Hello,

here we have two problems:

1. Unfortunately, partly generated metadata are not destroyed in case an error occurs during the metadata generation. Therefor a second call returns the part generated till the error occurred. This could also be empty.
2. Two of your navigations have no cardinality information sourceWorkflow and  targetWorkflow. I'm not sure if JPA supports this. At least the JPA Processor requires this information. So you may need to add the corresponding annotation. Meaningful error message is missing.

**Comment by Valeri-Velev** [comment]
Hello,

Can I help somehow?

**Comment by wog48** [comment]
With release 1.1.1, an error message has been added.
