### ISSUE TITLE
Spring Boot 3 support

### ISSUE THREAD

**Issue by theomoorman** [SAP/olingo-jpa-processor-v4#216]
Hi,

Spring Boot 3 / Spring 6 fully supports the Jakarta namespace and doesn't work with the old javax one. Also it has upgraded to Hibernate 6.
Apache Olingo is working on a new release with Jakarta support ([see](https://issues.apache.org/jira/browse/OLINGO-1600)).
Will this library then also be upgraded to work with Jakarta and then be tested with the new Spring Boot 3 stack?

Gr, Theo.

**Comment by wog48** [comment]
It is planned to create a new version based on Java 17 / Jakarta / Spring Boot3 after Olingo made that step.
