### ISSUE TITLE
Custom method to fetch entities

### ISSUE THREAD

**Issue by smiesnyrobert** [SAP/olingo-jpa-processor-v4#217]
Hi, exists some way how to fetch jpa entities using my own repository with my own custom logic and then convert them to odata or pass them to processor? 

eg.
``
List<MyEntity> entities  = myRepository.findByXXXX();
// this entities i want proccess to odata
``

Iam using spring boot, spring data

Thanks for help

**Comment by wog48** [comment]
Currently there is no hook to implement the retrieval of a certain entity. 

In general, your are able to use the metadata generation only and implement the retrieval of data on your own. You could also analyse the URI in the controller and direct, depending on the requested EntitySet, the request either to the JPA Processor or to an own implementation. To be honest, I haven't tried this.
