### ISSUE TITLE
Many to many support

### ISSUE THREAD

**Issue by nikolay-angeloff** [SAP/olingo-jpa-processor-v4#22]
Is there a @ManyToMany support or how can I achieve such navigation in OData

**Comment by wog48** [comment]
That should be possible. In OData you do not directly see that it is a Many To Many relation. You only get to know that it is N:M if you look at both entities, as each navigation property is a collection:
<NavigationProperty Name="..." Type="Collection(...)"

**Comment by nikolay-angeloff** [comment]
That's true and the navigation property is described well in the $metadata, but when I try to query the navigation items I get "No Join conditions where provided to create sub-query". That's because for ManyToMany in JPA I use Join Table

@ManyToMany(fetch = LAZY)
@JoinTable(name = "\"production_enterprise.production_enterprise_db::A_Bank_Clients\"",
            joinColumns = {@JoinColumn(name = "\"Bank_Id\"")},
            inverseJoinColumns = {@JoinColumn(name = "\"Person_Id\"")}) 

And when the processor is building the query it get's the Join Columns which are empty in this case.

**Comment by wog48** [comment]
Unfortunately as of now the join columns have to be given as fields in the java pojo. If you do not want it to be part of the OData service you can suppress that by using an additional annotation: @EdmIgnore. Maybe the following example helps:

```Java
        @EdmIgnore //Ignore field for metadata generation
	@Column(name = "\"BusinessPartnerID\"")
	private String businessPartnerID;

	@ManyToOne(optional = false, fetch = FetchType.LAZY)
	@JoinColumn(name = "\"BusinessPartnerID\"", insertable = false, updatable = false)
	private BusinessPartner businessPartner;
```

**Comment by nikolay-angeloff** [comment]
@wog48 

The join columns are in other table which isn't in the Entity that I'm targeting and the join table isn't represented as an entity itself. So does that mean that the ManyToMany mapping from JPA can't be represented in OData at this point, except with mapping the middle table and with ManyToOne from source and OneToMany from middle to the target entity?

**Comment by wog48** [comment]
I like to distinguish between OData an the JPA Processor here:

- OData, as shortly discussed above, only provides the multiplicity from the perspective of the entity type the navigation property is defined at. With this it is possible to create ManyToMany relations, as long as you do not want to provide the join table on your API. Otherwise you have to model the relations explicit. 
- JPA Processor is,  unfortunately,  as of now not able to handle join tables, but it is an interesting topic.

**Comment by wog48** [comment]
@nikolay-angeloff 
The new version 0.2.6 now supports join tables.

**Comment by yathihv** [comment]
Is this available in maven repository? can you please point me the dependency?

**Comment by mjza** [comment]
Any solution for this bug? 
https://stackoverflow.com/questions/62809753/olingo-v2-makes-exception-on-entities-with-manytomany-relationships
I am using Olingo V2, but it seems the error coming from JPA is problematic for Olingo.
