### ISSUE TITLE
$expand not work if $levels is specified

### ISSUE THREAD

**Issue by rayliu2007** [SAP/olingo-jpa-processor-v4#226]
when $levels is specified, $expand at same level is not working:
$expand=Children($levels=max;$expand=CodingBlockEntries)

**Comment by wog48** [comment]
Working on a fix, I noticed that the combination of $level together with an additional $expand not supported correctly by Olingo. I have created the following issue [OLINGO-1608](https://issues.apache.org/jira/browse/OLINGO-1608). The final solution of this issue requires the fix of OLINGO-1608.

**Comment by wog48** [comment]
Necessary preparation to solve this problem have been included in version 2.0.2. For further progress, a solution of  [OLINGO-1608](https://issues.apache.org/jira/browse/OLINGO-1608) is required. In case there will be still a problem, after OLINGO-1608 was solved, reopen this issue.
