### ISSUE TITLE
expand fail for v2.0.0

### ISSUE THREAD

**Issue by mbossX** [SAP/olingo-jpa-processor-v4#236]
```
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Role implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(length = 32, nullable = false)
    private String name;

    @Column(length = 128)
    private String comment;

    @Column(columnDefinition = "text")
    private String permissions;

    @OneToMany(mappedBy = "role")
    private List<User> users;
}

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class User implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(length = 32)
    private String name;

    private String email;

    @Column(length = 11, unique = true, nullable = false)
    private String username;

    @Column(length = 16, nullable = false)
    private String password;
    
    @Column(nullable = false, columnDefinition = "tinyint DEFAULT 0")
    private Integer status;

    @Column(name = "role_id")
    private Integer roleId;
    // @EdmIgnore
    // @Column(name = "role_id", precision = 10, insertable = false, updatable = false)
    // private Integer roleId;

    @ManyToOne
    @JoinColumn(name = "role_id", referencedColumnName = "id", insertable = false, updatable = false)
    private Role role;
}
```
when browser `http://localhost:8081/odata/v1/Users(1)?$expand=role`   
return    
`Could not determine recommended JdbcType for tech.jiyun.odata.entity.Role`
use v2.0.0 and springboot 3.1.5

but same code work fine at v1.1.1 and springboot 2.7.17

**Comment by mbossX** [comment]
@wog48 plase check this.

**Comment by mbossX** [comment]
spring-boot version is 3.1.5
dependencies show below:
```
<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>8.0.33</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.sap.olingo</groupId>
			<artifactId>odata-jpa-processor</artifactId>
			<version>2.0.0</version>
		</dependency>
	</dependencies>
```

**Comment by mbossX** [comment]
crash at   
 `com.sap.olingo.jpa.processor.core.query.JPAAbstractJoinQuery.java:642 createFromClauseNavigationJoins()`   
```
this.target = (From)this.target.as(cast.getTypeClass());

cast.getTypeClass() return "tech.jiyun.odata.entity.Role" but this.target.as crash
```

**Comment by mbossX** [comment]
[https://github.com/mbossX/ojp-issue-236](https://github.com/mbossX/ojp-issue-236)   

minimal test repo

**Comment by kumarvika** [comment]
Hi @mbossX, I am also facing the issue, but for me, the below line is at 747 in the same class and method.

target = (From<?, ?>) target.as(cast.getTypeClass());

Please do let me know if you find any solution. Thanks

**Comment by mbossX** [comment]
temporarily downgrade to version 1.1.1 and springboot 2.7.17.

**Comment by kumarvika** [comment]
Thanks, @mbossX, We are upgrading to implement Java 17 and Spring Boot 3. Thanks anyway.

**Comment by vijaykumaroutlook** [comment]
i am facing this issue with spring boot 3.1.5.

**Comment by DimitarTanev87** [comment]
I am facing similar issue with spring boot 3. 

@Table(name = "workflow")
class Activity {
....
  @OneToMany(mappedBy = "workflow", orphanRemoval = true, cascade = CascadeType.ALL)
  private List<ActivityLog> logs;
.....
}

@Table(name = "workflow_log")
class ActivityLog {
....
  @ManyToOne
  @JoinColumn(name = "workflow_id")
  private Activity workflow;
....

}

When execute ..../Activities?$top=2&$expand=Logs, I receive an error "The attribute [workflow_id] is not present in the managed type"

**Comment by wog48** [comment]
This is the same issue as described in [issue#238](https://github.com/SAP/olingo-jpa-processor-v4/issues/238). As explained there, this is seen as an issue of the Hibernate version comming with Spring Boot 3.x. You can try to use the JPA Processor own JPA Criteria Builder implementation [odata-jpa-processor-cb](https://github.com/SAP/olingo-jpa-processor-v4/tree/main/jpa/odata-jpa-processor-cb) by adding the corresonding dependency to you pom.

**Comment by vijaykumaroutlook** [comment]
Any one able to find a solution for this issue?

**Comment by wog48** [comment]
Please have a look at version 2.0.2.In case you still face the problem, reopen the issue
