### ISSUE TITLE
Filter query for startwith/contains doesn't work with not. 

### ISSUE THREAD

**Issue by keshavsahuzellis** [SAP/olingo-jpa-processor-v4#266]
Below query are not working.
?$filter=not startswith(FieldName,'XX') 
?$filter=startswith(FieldName,'XX') eq true
?$filter=not contains(FieldName,'XX')

**Comment by wog48** [comment]
I tested the query functions with my test data model. Unfortunately, I got the expected results. 
In general, it can be expected that the sum of the number of results for _not startswith_ and _startswith_ is the same as the overall number of results. So e.g.:
`AdministrativeDivisions/$count?$filter=not startswith(DivisionCode,'BE')` plus 
`AdministrativeDivisions/$count?$filter=startswith(DivisionCode,'BE'` should be the same as `AdministrativeDivisions/$count`. This holds true as long as the property does not contain NULL values. To my understanding, based on [5.1.1.1.9 Not](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#_Toc31360966), OData requires the same behavior for NULL values as SQL, they are ignored.

To have a deep er look at your problem, I would need to have some more details:

- Do you get an exception? And is so, which one?
- In case only some results are missing, do you have an idea what the differences are?
- Can you provide the generated SQL?

**Comment by keshavsahuzellis** [comment]
@wog48 , we can close this as it is working on latest build, Thanks for your response

**Comment by wog48** [comment]
Great news
