### ISSUE TITLE
JPAEDMExtension 

### ISSUE THREAD

**Issue by BitsofSid** [SAP/olingo-jpa-processor-v4#268]
is there a way for creating an extension to the JPA EDM schema for an OData service.  custom function imports, adds properties and complex types, and modifying the schema structure based on specific requirements

**Comment by BitsofSid** [comment]
Also any sample application (eclipselink)  /Documentation

**Comment by wog48** [comment]
Not sure, what intention is. 
The [quick start example](https://github.com/SAP/olingo-jpa-processor-v4/blob/main/jpa-tutorial/QuickStart/QuickStart.adoc) is a spring boot application that uses EclipseLink. For Complex Type you can have a look at [1.5 UsingComplexTypes](https://github.com/SAP/olingo-jpa-processor-v4/blob/main/jpa-tutorial/Tutorials/Metadata/1-5-UsingComplexTypes.md) and for Functions you can have a look at [1.8 Functions](https://github.com/SAP/olingo-jpa-processor-v4/blob/main/jpa-tutorial/Tutorials/Metadata/1-8-Functions.md).

Please re-open the ticked if you have additional questions
