### ISSUE TITLE
Slow connection with JTDS

### ISSUE THREAD

**Issue by nirliber** [SAP/olingo-jpa-processor-v4#27]
We are using JTDS version 1.3.1 and the connection management takes 6 seconds and it runs twice.
Trying to use Microsoft's JDBC driver was unsuccessful due to "connection is closed" error (despite the fact the connection URL and data source are legit).

The database is MSSql.

Please advice.

**Comment by wog48** [comment]
Due to clean-up action. All issues created before 2022 get closed.
