### ISSUE TITLE
Build Failure while following QuickStart

### ISSUE THREAD

**Issue by preston-jose** [SAP/olingo-jpa-processor-v4#274]
Have installed jpa using maven and also installed archetype (not with eclipse, cli).
Is there anything else missing in the quickstart?
![image](https://github.com/SAP/olingo-jpa-processor-v4/assets/25342586/703af712-078d-4f82-b608-0f5cafcb412c)

**Comment by wog48** [comment]
I assume that you have build the archetype using _mvn clean install archetype:update-local-catalog_. Nevertheless, it can happen that the local catalog is not updated. Please check if there is a _archetype-catalog.xml_ file within the _.m2_ directory. The file shall contain at least the following:

```<archetype-catalog xmlns="http://maven.apache.org/plugins/maven-archetype-plugin/archetype-catalog/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/plugins/maven-archetype-plugin/archetype-catalog/1.0.0 http://maven.apache.org/xsd/archetype-catalog-1.0.0.xsd">
  <archetypes>
    <archetype>
        <groupId>com.sap.olingo</groupId>
        <artifactId>odata-jpa-archetype-spring</artifactId>
        <version>2.1.0</version>
    </archetype>
  </archetypes>
</archetype-catalog>
```

**Comment by wog48** [comment]
Please re-open the issue if the give hint does not help
