### ISSUE TITLE
Can enable upsert?

### ISSUE THREAD

**Issue by ghost** [SAP/olingo-jpa-processor-v4#285]
enable upsert for PATCH and PUT request?

**Comment by wog48** [comment]
Actually, the JPA Processor it self does not handle Create, Update, Delete or Upsert requests. The provided `JPAExampleCUDRequestHandler` shall support rapide prototyping and is not foreseen for productive usage. In case you are in a hurry, copy the class and adopt implementation of `updateEntity` accordingly.

**Comment by rayliu2007** [comment]
Changing `updateEntity` is what I am doing.
While according to OData protocol: https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_UpsertanEntity, upsert is defined. So it will be better if it can be supported originally from this JPAExampleCUDRequestHandler?

**Comment by wog48** [comment]
I agree, it would better. Therefore I marked this as enhancement. Nevertheless, I like to point out, that JPAExampleCUDRequestHandler is just for **prototyping**.

**Comment by wog48** [comment]
The option to perform Upsert was added to JPAExampleCUDRequestHandler.
