### ISSUE TITLE
how to get only odata count without value

### ISSUE THREAD

**Issue by chentopf** [SAP/olingo-jpa-processor-v4#29]
Is there any way I can get only count of the data in response payload without any value array?

I just need something like "@odata.count":1, "value":[] or without "value".

I tried $count=true&$top=0
or Projects/count

as I saw on some blogs.
But it didn't work

Please assist...

**Comment by wog48** [comment]
The right way would be `Projects/$count`. 
Without the $ its not an OData function and is ignored.

**Comment by Falseclock** [comment]
@chentopf, did you get it working?

Mine not, getting error `<message>Error occurred validating the Criteria</message>`

**Comment by chentopf** [comment]
Yes it is working for me

**Comment by Falseclock** [comment]
That is strange, cause getting error "No criteria query roots were specified" on this line from 

https://github.com/SAP/olingo-jpa-processor-v4/blob/5873bd241caaa3698777731aaeb176a56f0542a8/jpa/odata-jpa-processor/src/main/java/com/sap/olingo/jpa/processor/core/query/JPAJoinQuery.java#L71

**Comment by wog48** [comment]
I ran an example locally with EclipseLink as JPA implementation and it worked fine. Do you use  Hibernate?

**Comment by Falseclock** [comment]
@wog48, yes, v5.2.14

**Comment by wog48** [comment]
There is an error in the code. To be honest it is unclear to me why EclipseLink works fine. I will provide a fix.

**Comment by wog48** [comment]
The fix is part of latest release 0.2.7.

**Comment by chentopf** [comment]
Thanks!
when do you plan to add it to maven repository?
