### ISSUE TITLE
CreateEntity when PrimaryKey is provided

### ISSUE THREAD

**Issue by nico525** [SAP/olingo-jpa-processor-v4#30]
Hi,

I am currently struggling with setting up an Data interface for an existing application. Unfortunately, it is providing a dummy value for the ID as soon as I want to create a new Entity. This CREATE results in the error message "Invalid value for property 'IdProduct'."
Is there any way around this? I cannot even reach the createEntity method when providing the ID

**Comment by wog48** [comment]
Hello,

this is a message coming from Olingo. The message seems to belong to DeserializerException, with the message key INVALID_VALUE_FOR_PROPERTY. In case you sending a JSON it is very likely that the message is raised in  ODataJsonDeserializer readPrimitiveValue. 
Depending on the type of 'IdProduct' the apostrophe are missing or you have to remove them.

**Comment by nico525** [comment]
Actually, this Message can be debugged down to JPA. I referenced nullable Integers to the primitive int which (obviously) cannot be null

Anyway, thanks for your response.
