### ISSUE TITLE
version 2.1.0 is incompatible with Oracle Database

### ISSUE THREAD

**Issue by sungongpeng** [SAP/olingo-jpa-processor-v4#307]
Version 2.1.0
Database: Oracle 19c
**Issue 1:  query build**
appending "OFFSET n LIMIT m"  to a query, This is incorrect for Oracle database.

For Oracle, the correct 
SELECT * FROM TABLE offset n rows FETCH NEXT m rows ONLY

**Issue 2: $count** 
got error:
class java.math.BigDecimal cannot be cast to class java.lang.Long (java.math.BigDecimal and java.lang.Long are in module java.base of loader 'bootstrap'

**Comment by sungongpeng** [comment]
look like Pull Request 
https://github.com/SAP/olingo-jpa-processor-v4/pull/303
would fix Issue 2: $count

Issue 1: query build
need a fix for oracle, like the fix for Sysbase in pull/303

**Comment by wog48** [comment]
For a quick fix you remove module [odata-jpa-processor-cb](https://github.com/SAP/olingo-jpa-processor-v4/tree/main/jpa/odata-jpa-processor-cb) from you pom.xml or gradle file.

Try to generalize PR 303

**Comment by wog48** [comment]
The latest changes in version 2.2.0 should solve the problem with OFFSET and LIMIT. Please be aware that also OData _indexof_, which is converted by default into SQL _locate_, and OData _substring_, by default converted into SQL _substring_, may cause issues with Oracle. In case you need them, an implementation of [ProcessorSqlPatternProvider](https://github.com/SAP/olingo-jpa-processor-v4/blob/main/jpa/odata-jpa-processor-ext/src/main/java/com/sap/olingo/jpa/processor/cb/ProcessorSqlPatternProvider.java) needs to be provided via the [session context](https://github.com/SAP/olingo-jpa-processor-v4/blob/decffc8d89faecd8f00b7201fc8f88b8c8b5da05/jpa/odata-jpa-processor/src/main/java/com/sap/olingo/jpa/processor/core/api/JPAODataServiceContext.java). You can use [JPADerbySqlPatternProvider](https://github.com/SAP/olingo-jpa-processor-v4/blob/decffc8d89faecd8f00b7201fc8f88b8c8b5da05/jpa/odata-jpa-processor/src/main/java/com/sap/olingo/jpa/processor/core/database/JPADerbySqlPatternProvider.java) or [JPAPostgresqlSqlPatternProvider](jpa/odata-jpa-processor/src/main/java/com/sap/olingo/jpa/processor/core/database/JPAPostgresqlSqlPatternProvider.java) as an example.

**Comment by wog48** [comment]
The issue shall be fixed with 2.2.0
