### ISSUE TITLE
Can We create Versioning  on specific to GET API call ?

### ISSUE THREAD

**Issue by suraj-mane-zellis** [SAP/olingo-jpa-processor-v4#308]
Can We do versioning on entity ? Suppose I have added new entity , I want to show this entity in different version .
https://www.postman.com/api-platform/api-versioning/

**Comment by suraj-mane-zellis** [comment]
Hi @wog48  , Can we display only certain fields using any EDM annotation ? I dont want to use @edmIgnore because I want show those fields conditionally

**Comment by suraj-mane-zellis** [comment]
HI @wog48 ,

I am waiting for your valuable response from long time . Is there any implementation in  jpa processor to achieve URL based versioning ?

**Comment by wog48** [comment]
Sorry for the late response. 

It turned out that the original idea for versioning does not work. New one is under development.

**Comment by wog48** [comment]
In 2.3.0 API versioning was added. It is described in [How to handle API sersions?](https://github.com/SAP/olingo-jpa-processor-v4/blob/main/jpa-tutorial/Questions/HowToHandleApiVersions.adoc). 
It is up to you how a client provides which version is addressed. If it is a URL parameter  or a header.
