### ISSUE TITLE
$filter pushed down to SQL or executed in the library?

### ISSUE THREAD

**Issue by ericraskin** [SAP/olingo-jpa-processor-v4#31]
1) Is the $filter added to the SQL so that the database providing the data can process it?

Or

2) Does the database return ALL data and then the $filter is processed in your code?

Because if #1 is the answer then the operation is exceedingly slow for large tables.  I have table of about 1.8 million rows and I want to $filter out 50.  That would be quick inside my Oracle database (due to indexes) but would take forever if all 1.8 million rows get loaded into my Tomcat server.

How does it work?

**Comment by wog48** [comment]
$filter is pushed down to the database. The source code can be found in package  `com.sap.olingo.jpa.processor.core.filter`. If you like you can have a look at the generated SQL by switching on the corresponding logs in the `persistence.xml`:
EclipseLink:
```XML
<properties>
    <property name="eclipselink.logging.level.sql" value="FINEST" />
    ...
</properties>
```
Hibernate:
```XML
<properties>
   <property name="hibernate.show_sql" value = "true" />
   <property name="hibernate.format_sql" value="true"/>
    ...
</properties>
```
Generally the motto is: Let the database do what it can do best.

**Comment by ericraskin** [comment]
OK, thank you.  



---------------------------------------------------------------------------------------------------------------------------------------------

Eric H. Raskin                                                                                                      914-765-0500 x120

Professional Advertising Systems Inc.                                                                 914-765-0503 fax

200 Business Park Drive Suite 304                                                                     eraskin@paslists.com

Armonk, NY 10504                                                                                              http://www.paslists.com





-----Original message-----

**Comment by wog48** [comment]
As it look like the problem was solved, the issue get closed.
