### ISSUE TITLE
OutOfMemory  - Expanded more entities in server driven paging

### ISSUE THREAD

**Issue by suraj-mane-zellis** [SAP/olingo-jpa-processor-v4#314]
I have gone through the link https://github.com/SAP/olingo-jpa-processor-v4/blob/main/jpa-tutorial/Tutorials/SpecialTopics/4-3-ServerDrivenPaging.md where in you mentioned that **As of now paging for expanded to-many navigation properties is not supported.** 
            We are having little bit huge data in some of expaned entities and I am getting out of memory exception . Is there way out to handle this issue?

**Comment by suraj-mane-zellis** [comment]
HI @wog48 , I am waiting for your valuable response.

**Comment by wog48** [comment]
I had a first look. Indroducting Server driven paging is not a low hanging fruit.  
The only hint, for the momement I can give, is to limt number of parents.

**Comment by wog48** [comment]
I have to mention that the solution will only work together with  odata-jpa-processor-cb as JPA dies not support LIMIT and OFFSET on sub queries.
What database do you use?

**Comment by suraj-mane-zellis** [comment]
Hi @wog48 ,

I am using Azure SQL database

**Comment by wog48** [comment]
With 2.2.0 server-driven paging is supported on $expand. How to make use of it is described in [How to build server-driven paging for $expand?](https://github.com/SAP/olingo-jpa-processor-v4/blob/main/jpa-tutorial/Questions/HowToBuildServerDrivenPagingExpand.adoc)
