### ISSUE TITLE
expand inside an expand

### ISSUE THREAD

**Issue by chentopf** [SAP/olingo-jpa-processor-v4#32]
Hi,
Is there a way to expand entity from an expand entity.
Meaning to expand more than one layer.
for example : 
/Projects?$expand=Scan

now i also would like to expand things from scan
Is it possible?

Thanks,
Chen

**Comment by wog48** [comment]
Hello,

with OData v4 this is possible. 

In your example this may look like `/Projects?$expand=Scan($expand=Foo)`.
In principle you are allowed to do that as deep as you want. To take an example from the tutorials:
`AdministrativeDivisions(DivisionCode='33016',CodeID='LAU2',CodePublisher='Eurostat')?$expand=Parent($expand=Parent($expand=Parent))`. With that you can also get the siblings e.g. of BE25:
`/AdministrativeDivisions(DivisionCode='BE25',CodeID='NUTS2',CodePublisher='Eurostat')?$expand=Parent($expand=Children)`. But it should also be handled with care, as each level increases the amount of data that needs to be handled.

Regards,
Oliver
