### ISSUE TITLE
v2.1.0, $count is not working whatsoever; pagination is not working

### ISSUE THREAD

**Issue by akaFood** [SAP/olingo-jpa-processor-v4#330]
when using $count = true or enable paginaiton, the following error is returned:
 "class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')". 
The error was thrown at JPAExamplePagingProvider.class, getFirstPageMethod, Long maxResults = countQuery.countResults();. 
Inside JPAJoinCountQuery.class,  line 47 - return (Long) result.get(0); I saw that the total records count returned was Integer type, and its getting casted to Long, hence why the error occurred.

![Screenshot 2024-06-13 123549](https://github.com/SAP/olingo-jpa-processor-v4/assets/164376839/cf8bec3a-59ac-4579-bafc-e0e1920b63bf)

**Comment by wog48** [comment]
What database do you use?

**Comment by akaFood** [comment]
> What database do you use?

DB2

**Comment by wog48** [comment]
The latest changes in version 2.2.0 should solve the problem with OFFSET and LIMIT. Please be aware that also OData indexof, which is converted by default into SQL locate, and OData substring, by default converted into SQL substring, may cause issues with Oracle. In case you need them, an implementation of [ProcessorSqlPatternProvider](https://github.com/SAP/olingo-jpa-processor-v4/blob/main/jpa/odata-jpa-processor-ext/src/main/java/com/sap/olingo/jpa/processor/cb/ProcessorSqlPatternProvider.java) needs to be provided via the [session context](https://github.com/SAP/olingo-jpa-processor-v4/blob/decffc8d89faecd8f00b7201fc8f88b8c8b5da05/jpa/odata-jpa-processor/src/main/java/com/sap/olingo/jpa/processor/core/api/JPAODataServiceContext.java). You can use [JPADerbySqlPatternProvider](https://github.com/SAP/olingo-jpa-processor-v4/blob/decffc8d89faecd8f00b7201fc8f88b8c8b5da05/jpa/odata-jpa-processor/src/main/java/com/sap/olingo/jpa/processor/core/database/JPADerbySqlPatternProvider.java) or [JPAPostgresqlSqlPatternProvider](https://github.com/SAP/olingo-jpa-processor-v4/issues/jpa/odata-jpa-processor/src/main/java/com/sap/olingo/jpa/processor/core/database/JPAPostgresqlSqlPatternProvider.java) as an example.
