### ISSUE TITLE
mvn clean install archetype:update-local-catalog is failing. getting Archetype IT 'createWithAllParameter' failed: Execution failure: exit code = 1 error. 

### ISSUE THREAD

**Issue by Nismath** [SAP/olingo-jpa-processor-v4#348]
@wog48   [INFO] [ERROR] Failed to execute goal on project withParameter: Could not resolve dependencies for project com.test:withParameter:jar:0.0.1: The following artifacts could not be resolved: com.sap.olingo:odata-jpa-processor:jar:2.2.0-SNAPSHOT (absent), com.sap.olingo:odata-jpa-processor-cb:jar:2.2.0-SNAPSHOT (absent), com.sap.olingo:odata-jpa-spring-support:jar:2.2.0-SNAPSHOT (absent): Could not find artifact com.sap.olingo:odata-jpa-processor:jar:2.2.0-SNAPSHOT -> [Help 1]

**Comment by oleg-duvanayev** [comment]
hey,
I experienced the same issue:

![image](https://github.com/SAP/olingo-jpa-processor-v4/assets/17144584/53f06f8d-cc8f-4058-9e40-03682baefddb)

regards

**Comment by Nismath** [comment]
@oleg-duvanayev are you able to fix it?

**Comment by oleg-duvanayev** [comment]
> @oleg-duvanayev are you able to fix it?

no, I am not a developer of that project.

**Comment by wog48** [comment]
The maven command will only update the catalog, but not creating it. Pleas check if you have archetype-catalog.xml file in your .m2 folder. If not you need to created it. In this case you can immediately use enter the artifact: 

```
<archetype-catalog xmlns="http://maven.apache.org/plugins/maven-archetype-plugin/archetype-catalog/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/plugins/maven-archetype-plugin/archetype-catalog/1.0.0 http://maven.apache.org/xsd/archetype-catalog-1.0.0.xsd">
  <archetypes>
    <archetype>
        <groupId>com.sap.olingo</groupId>
        <artifactId>odata-jpa-archetype-spring</artifactId>
        <version>2.2.0-SNAPSHOT</version>
    </archetype>
  </archetypes>
</archetype-catalog>
```

**Comment by Nismath** [comment]
I have already created the archetype-catalog.xml. but still, my build fails when I try to execute the mvn clean install archetype:update-local-catalog command

**Comment by oleg-duvanayev** [comment]
hi @wog48 
many thanks for your response.
Yes, initially as described in QuickStart, I created the file archetype-catalog.xml. The only difference to your one above is the version. As described in QuickStart I use the 2.1.3
![image](https://github.com/SAP/olingo-jpa-processor-v4/assets/17144584/772f62ee-c0da-4ba3-8be5-724378db72e4)

Nevertheless, I have updated my local file ~/.m2/archetype-catalog.xml to your version and repeat the "mvn install" again.
Unfortunately, it fails:

`~>  mvn -s ~/.m2/archetype-catalog.xml clean install archetype:update-local-catalog`
![image](https://github.com/SAP/olingo-jpa-processor-v4/assets/17144584/9b50e979-76b6-48e5-892d-449d2183ec81)
![image](https://github.com/SAP/olingo-jpa-processor-v4/assets/17144584/18cd3905-a3b6-4734-aa60-a03e1c6602a5)


Could you please for test purposes only do remove the meaning artifact from your repo and try the same command again?

best regards

**Comment by oleg-duvanayev** [comment]
hi @wog48 

might you have a specific setting in ~/.m2/settings.xml , which we don't have?

Maven usually likes to have some additional declarations in that file.

best regards.

**Comment by oleg-duvanayev** [comment]
hello @Nismath , have you managed to solve the issue?

regards

**Comment by Nismath** [comment]
@oleg-duvanayev yes. before running the mvn clean install archetype:update-local-catalog cmd. I ran the mvn clean install for the JPA module. then ran the archtype cmd. it worked for me.

**Comment by oleg-duvanayev** [comment]
hey @Nismath, thanks to your recommendation I have managed to compile the archetype as well, but have you completed the next steps from the [Quick Start](https://github.com/SAP/olingo-jpa-processor-v4/blob/main/jpa-tutorial/QuickStart/QuickStart.adoc)?
I am about the generation the project based on the archetype _odata-jpa-archetype-spring_. This step doesn't work for me, even if I do it from the CLI
`~> mvn archetype:generate -DarchetypeArtifactId=odata-jpa-archetype-spring`

could you please check it on your local?

regards

**Comment by Nismath** [comment]
Hello @oleg-duvanayev ,

I created the project with the latest release 2.1.3

`mvn archetype:generate -DarchetypeGroupId=com.sap.olingo -DarchetypeArtifactId=odata-jpa-archetype-spring -DarchetypeVersion=2.1.3`
