### ISSUE TITLE
NavigationLinks for navigated properties in JSON output

### ISSUE THREAD

**Issue by Falseclock** [SAP/olingo-jpa-processor-v4#35]
With JSON output there is no any navigationLinks for navigated properties.

http://docs.oasis-open.org/odata/odata-json-format/v4.0/odata-json-format-v4.0.html#_Toc453766637

Am I missing something in Entity definition or it is not implemented yet?

**Comment by Falseclock** [comment]
Navigation links are appear if use $expand

![image](https://user-images.githubusercontent.com/3299139/37295184-b71b0de2-2641-11e8-8be7-3a998182e417.png)

But all of them are null.

If remove $expand they also disappear, **while should not.**

![image](https://user-images.githubusercontent.com/3299139/37295254-e7132a84-2641-11e8-9921-c18b7ccb75df.png)

**Comment by wog48** [comment]
I try to get in contact with the people from Olingo to clarify that.

**Comment by wog48** [comment]
Got some feedback from Olingo and it sound that the JPA Processor always need to create the Navigation Link annotation even it no $expand was send. If that is true I will create a fix.

**Comment by Falseclock** [comment]
yes, it is true.

And would be perfect if it can be adjustable with some settings.

For example I used to see navigation links even with odata.metadata=minimal

**Comment by wog48** [comment]
Version 0.2.8 contains a fix. Please be aware that this currently not working for navigation properties being part of complex properties, see [OLINGO-1248](https://issues.apache.org/jira/browse/OLINGO-1248).
