### ISSUE TITLE
Is it possible to store the skiptoken structure in an external storage?

### ISSUE THREAD

**Issue by yakut** [SAP/olingo-jpa-processor-v4#360]
We need to scale the application, but we encountered a problem with storing the skiptoken in the local Map structure of a single application instance. When trying to serialize the JPAODataPage object, we face serialization errors due to cyclic dependencies.

Would you happen to have any advice on how to store JPAODataPage in external storage?

**Comment by yakut** [comment]
Hi @wog48.  I understand that you are busy, but maybe the answer/advice to my question will be quick

**Comment by wog48** [comment]
Actually you are free to use any storage. I wrote a tutorial with my thought and experiences:  [How To Build Server Driven Paging](https://github.com/SAP/olingo-jpa-processor-v4/blob/main/jpa-tutorial/Questions/HowToBuildServerDrivenPaging.adoc). Prerequisite is version 2.1.0. 

I hope this helps.

**Comment by yakut** [comment]
Thanks a lot, your documentation is handy
