### ISSUE TITLE
Artifact not found in maven repo 

### ISSUE THREAD

**Issue by ib-haseeb** [SAP/olingo-jpa-processor-v4#365]
Hi all,

im experiencing this problem(not able download or find the artifact in the maven repo: com.sap.olingo odata-jpa-processor ), why this is not uploaded in maven central?

we can do mvn build and works but only in local, it would be optimal if this can be uploaded on maven central
Is there any prevision to be uploaded on maven repository?

Thanks in advance

**Comment by wog48** [comment]
This is work in progress. I'm not able to predict when this is finished.
