### ISSUE TITLE
Group by : $apply & $groupby

### ISSUE THREAD

**Issue by ib-haseeb** [SAP/olingo-jpa-processor-v4#372]
We are trying to implement this processor to use odata and we can see that $apply=groupby((Score),aggregate($count as total)) is not working. 

"'$apply' is not implemented"

Is there any plan to implement $apply & $groupby in this library?

FYA @wog48 

Thanks in advance.

**Comment by wog48** [comment]
As of now there are no concrete planes to implement the Data Aggregation extension.
