### ISSUE TITLE
$expand with $count fails when having a join table

### ISSUE THREAD

**Issue by wog48** [SAP/olingo-jpa-processor-v4#376]
When trying to get the number of expand entities e.g., .../entitySet?$expand=navigation($count=true), the service response with a http 500. The error message states:

_ON condition right attribute is null / not found._

**Comment by dbhandari555** [comment]
Can you please provide an example for the above mentioned scenario using the entities defined in sap-jpa project? I can't reproduce the issue. For example, I tried `Organizations?$expand=Roles($count=true)` and it succeeds without error.

**Comment by wog48** [comment]
@dbhandari555 The example you use has no join table. Try `JoinSource?$expand=OneToMany($count=true)`.

**Comment by dbhandari555** [comment]
ok I got you. I can see the reproduce with JoinSources?$expand=OneToMany($count=true)

**Comment by wog48** [comment]
The issue shall be fixed with 2.2.0
