### ISSUE TITLE
Resource leak reported by Coverity Polaris on SAP Olingo 2.1.1

### ISSUE THREAD

**Issue by arpithnayak** [SAP/olingo-jpa-processor-v4#378]
![Screenshot](https://github.com/user-attachments/assets/d620f3ef-70cd-44d1-9e1e-9579828434bb)

**Comment by wog48** [comment]
Will be solved. Luckily the code is part of an disabled test.

**Comment by wog48** [comment]
The issue shall be fixed with 2.2.0
