### ISSUE TITLE
Is there a way to automatically generate an Entity and load it into a Spring Context?

### ISSUE THREAD

**Issue by yz271544** [SAP/olingo-jpa-processor-v4#38]
If I want to use Spring boot and Hibernate integration the table in the database is automatically published as a RESTful service.  So how can an Entity be automatically generated and loaded into a Spring context?

**Comment by Falseclock** [comment]
what do you mean 

> utomatically generated and loaded

**Comment by yz271544** [comment]
What should I do, if I want to dynamically publish a table as a REST API, when the service is started ? E.g get the information from database to generate entity.

**Comment by Falseclock** [comment]
It's theoretically possible but what would be the point? Java is statically typed so you would only be able to use the generated classes by reflection and you would have no way of giving them behaviour, so removing the whole point of object-relational mapping. 

All IDEs have plugins to generate entities from existing database source. I think it is more appropriate method for entities generation.

**Comment by yz271544** [comment]
Thank you very much !!! For traditional enterprise customers, who lack IT development capabilities and want to publish their own data as RESTful services. We must consider using other solutions.
