### ISSUE TITLE
JSON value representation

### ISSUE THREAD

**Issue by Falseclock** [SAP/olingo-jpa-processor-v4#39]
Let's imagine I have a column which holds JSON/JSONB representation of internal information for triggering or caching policy handling, whatever.
Let's imagine also a lot of tables have such column. From table to table 80% of information has the same structure. For example:

```json
{
   "date_created":"2017-12-28 16:15:48.381194+06",
   "date_updated":"2017-12-08 17:42:33.133355+06",
   "is_active":true,
   "is_withdrawn":false,
   "premission_type":"SPECIAL",
   "cache_key":"some_unique_cache_key",
   "cache_expiration":"3600"
}
```

Of course JSON type if not supported by Olingo according to https://olingo.apache.org/javadoc/odata4/org/apache/olingo/commons/api/edm/EdmPrimitiveType.html
and I have to treat it as STRING. But Apache can't process big structures and produces an error in https://github.com/apache/olingo-odata4/blob/d9aff6300f61750d7f1a20d8ae58c322d8cde4e3/lib/server-core/src/main/java/org/apache/olingo/server/core/serializer/xml/ODataXmlSerializer.java#L857

Will report issue on Apache later.

So finally, querying entity getting this
```json
{
   "@odata.context":"$metadata#Table_Companies",
   "value":[
      {
         "Data":"{ \"date_created\":\"2017-12-28 16:15:48.381194+06\", \"date_updated\":\"2017-12-08 17:42:33.133355+06\", \"is_active\":true, \"is_withdrawn\":false, \"premission_type\":\"SPECIAL\", \"cache_key\":\"some_unique_cache_key\", \"cache_expiration\":\"3600\"} ",
         "Identity":"1234567890123",
         "Name":"Company #1",
         "Id":4,
         "LegalFormId":1
      },
      {
         "Data":"{ \"date_created\":\"2017-12-28 16:15:48.381194+06\", \"date_updated\":\"2017-12-08 17:42:33.133355+06\", \"is_active\":true, \"is_withdrawn\":false, \"premission_type\":\"SPECIAL\", \"cache_key\":\"some_unique_cache_key\", \"cache_expiration\":\"3600\", \"another_key\": true}",
         "Identity":"120640010032",
         "Name":"Company #2",
         "Id":2,
         "LegalFormId":3
      }
   ]
}
```

Is there any idea how to get structure like this

```json
{
   "@odata.context":"$metadata#Table_Companies",
   "value":[
      {
         "Data":{
            "date_created":"2017-12-28 16:15:48.381194+06",
            "date_updated":"2017-12-08 17:42:33.133355+06",
            "is_active":true,
            "is_withdrawn":false,
            "premission_type":"SPECIAL",
            "cache_key":"some_unique_cache_key",
            "cache_expiration":"3600"
         },
         "Identity":"1234567890123",
         "Name":"Company #1",
         "Id":4,
         "LegalFormId":1
      },
      {
         "Data":{
            "date_created":"2017-12-28 16:15:48.381194+06",
            "date_updated":"2017-12-08 17:42:33.133355+06",
            "is_active":false,
            "is_withdrawn":true,
            "premission_type":"INTERNAL",
            "cache_key":"some_unique_cache_key",
            "cache_expiration":"300",
            "SPECIAL_KEY_ONLY_FOR_THIS_ROW":true
         },
         "Identity":"120640010032",
         "Name":"Company #2",
         "Id":2,
         "LegalFormId":3
      }
   ]
}
```

I think I can use ComplexType but still not sure how to implement it and handle non standart keys like SPECIAL_KEY_ONLY_FOR_THIS_ROW

Any ideas?

**Comment by wog48** [comment]
To be honest what you like to do is not supported by the jpa processor. If I got it right you like to store the data in a hybrid way. One part as separate columns and another part as JSON. In addition I assume that a client won’t be able to filter on the JSON properties. I once had the idea to enable something like that by a combination of suppressing the JSON attribute from being part of the $metadata document by using @EdmIgnore and marking the embeddable with @Transient, but this has no priority on my list.
Nevertheless, two options came into my mind, but both are not supported by the jpa processor and so I do not know if they are supported by Olingo:
1.	Odata provides the annotation [AdditionalProperties]( https://github.com/oasis-tcs/odata-vocabularies/blob/master/vocabularies/Org.OData.Core.V1.md#AdditionalProperties), which indicates that an instance may contain properties in addition to those declared in $metadata. You are able to create the annotation by annotating the corresponding emebbable as follows: `@EdmAnnotation(term = "Core.AdditionalProperties", constantExpression = @EdmAnnotation.ConstantExpression( type = ConstantExpressionType.Bool, value = "true"))`
2.	You miss use [Open Type](http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part3-csdl/odata-v4.0-errata03-os-part3-csdl-complete.html#_6.1.4_The_edm:OpenType), which would allow a client to add properties, but who knows how the property “SPECIAL_KEY_ONLY_FOR_THIS_ROW” made it into “Data” structure.

**Comment by wog48** [comment]
Due to clean-up action. All issues created before 2022 get closed.
