### ISSUE TITLE
Function import doesn't work with with java classes in OSGi

### ISSUE THREAD

**Issue by JackTack** [SAP/olingo-jpa-processor-v4#40]
The code which is described in tutorilal [https://github.com/SAP/olingo-jpa-processor-v4/blob/develop/jpa-tutorial/Tutorials/Metadata/1-8-Functions.md](url) doesn't add function import to metadata.  
Here is the code:
`			
				EntityManagerFactory emf = JPAEntityManagerFactory.getEntityManagerFactory(PUNIT_NAME,ds);
				EntityManager	em = emf.createEntityManager();
				JPAODataCRUDHandler handler = new JPAODataCRUDHandler(PUNIT_NAME);	
				handler.getJPAODataContext().setTypePackage("mypackage.functions");
				handler.getJPAODataContext().initDebugger(PUNIT_NAME);
				handler.process(req, resp, em);
			`

**Comment by wog48** [comment]
Do you get a <Function Name="..."> in your metadata document?

**Comment by JackTack** [comment]
Important addition. Function import doesn't work only inside OSGI container. Outside the container everything goes well. I had to check this first. Sorry.
