### ISSUE TITLE
The queries on expanded entities/collections are triggered despite the core entity result being empty

### ISSUE THREAD

**Issue by dbhandari555** [SAP/olingo-jpa-processor-v4#406]
Lets elaborate with a simple example using entities defined in the library :  `Organizations?$top=0&$expand=Roles`

This will deterministically return empty results when query.execute() is performed on the core entity. Currently, there is no check in JPANavigationRequestProcessor class to verify if the core entity result set is empty before proceeding with triggering the subsequent queries on the associated collections of the core entity or the expanded entity. This results in unnecessary computation on the server side since the overall result is always empty.

**Comment by dbhandari555** [comment]
Solution for the same proposed here: https://github.com/SAP/olingo-jpa-processor-v4/pull/408

**Comment by wog48** [comment]
Pull request was merged. Thanks for supporting
