### ISSUE TITLE
$metadata with accept header json

### ISSUE THREAD

**Issue by chentopf** [SAP/olingo-jpa-processor-v4#42]
Hi,
Calling $metadata with Accept header with value: application/json causing:
 "message": "The content-type range 'application/json' is not supported as value of the Accept header.",
    "code": 406

Is there a way to support json response for $metadata as well?

Thanks,
Chen

**Comment by wog48** [comment]
I do not know a way. Anyhow this is a topic for Olingo, as the serialization is done in that part. 

I found the issue [OLINGO-570](http://docs.oasis-open.org/odata/new-in-odata/v4.01/cn02/new-in-odata-v4.01-cn02.html#_Toc495652541) about Json Metadocument Serializer/Parser, which is still open.

**Comment by Falseclock** [comment]
@chentopf  it is not supported according to ODATA standard. Metadata should be always XML

**Comment by wog48** [comment]
Officially this comes with OData 4.01. You can find it e.g. [What’s New in OData Version 4.01](http://docs.oasis-open.org/odata/new-in-odata/v4.01/cn02/new-in-odata-v4.01-cn02.html#_Toc495652541). This is maybe also a reason why its not yet there.

**Comment by chentopf** [comment]
I meant when you are going to publish olingo-jpa-proccessor to maven

**Comment by wog48** [comment]
Due to clean-up action. All issues created before 2022 get closed.
