### ISSUE TITLE
2.3.0 version - Duplicate orderBy key generated in sql query when URL Query Parameter contains orderBy and top.

### ISSUE THREAD

**Issue by keshavsahuzellis** [SAP/olingo-jpa-processor-v4#424]
Query : 
/Entity?$**orderby**=EntityPrimaryId desc&$**top**=5

Error : 
{
    "error": {
        "code": null,
        "message": "JDBC exception executing SQL [select top (?) p1_0.[XXX],p1_0.[PostId],p1_0.[XXX] from [tx].[XXX] p1_0 where p1_0.[XX]=? order by 2 desc,2] [A column has been specified more than once in the order by list. Columns in the order by list must be unique.] [n/a]"
    }
}

**Comment by wog48** [comment]
Version 2.3.1 is now available. In case the issue is not final fixed, reopen the issue.
