### ISSUE TITLE
How can I query on filter date fields

### ISSUE THREAD

**Issue by wu244534279** [SAP/olingo-jpa-processor-v4#44]
Hello,when I request as url : $filter=StartDate eq datetime'2018-03-31T22:22:00'
it reponse message:The property 'datetime',use in a query  expression,is not defined in type ......

**Comment by yathihv** [comment]
use something like - $filter=field_name gt 2018-02-22T00:00:00Z

**Comment by wog48** [comment]
Due to clean-up action. All issues created before 2022 get closed.
