### ISSUE TITLE
Server side paging: broken link on the next page

### ISSUE THREAD

**Issue by reket** [SAP/olingo-jpa-processor-v4#48]
Hi!

We  were faced with one problem during server side pagination testing. Link on the next page is broken:

Actual result (by this link we can't get result):

`    "@odata.nextLink": "MediaEntities?$skiptoken='1c038bc8-bb6a-4ac0-8253-9f4117ceb9f1'"`

Expected result (skip token should be without single quotes and by this link we can get result):

`    "@odata.nextLink": "MediaEntities?$skiptoken=1c038bc8-bb6a-4ac0-8253-9f4117ceb9f1"`

**Comment by wog48** [comment]
Due to clean-up action. All issues created before 2022 get closed.
