### ISSUE TITLE
Server side pagination is not working in combination with $select

### ISSUE THREAD

**Issue by olegkudriavtsev** [SAP/olingo-jpa-processor-v4#49]
We are creating API using Spring Data. In entity we have some columns which marked as not null.
After sending query with $select option we got an exception that non nullable property is missing(The non-nullable property <non nullable property name> is missing.).

**Comment by wog48** [comment]
Hello,

I had a look at pagination and $select. I found a problem in case another page than the first one is requested. In that case the select option is not correctly forwarded to the serializer. I'm working on a fix. I hope you do not face the problem on the first page.

**Comment by wog48** [comment]
Due to clean-up action. All issues created before 2022 get closed.
