### ISSUE TITLE
filter contains not working with SQL server

### ISSUE THREAD

**Issue by nico525** [SAP/olingo-jpa-processor-v4#52]
Hi,

I have a SQL Server up and running. I am somehow able to connect to that OData interface, but my API is creating filters similar to this: "$filter=contains(Name, '3') eq true"
This does result in very weird SQL queries (see below) which result in an SQL exception, because SQL Server is not capable to run them. The same does work on MySQL, but as being said, we are using SQL Server... Is there any way to deal with that?

```
SELECT NAME FROM STRATEGY WHERE (NAME LIKE ? = ?) LIMIT ?, ?
    bind => [%3%, true, 0, 201]
```

**Comment by wog48** [comment]
Due to clean-up action. All issues created before 2022 get closed.
