### ISSUE TITLE
Context should give full root URL; if the service won't be processed by BI tools

### ISSUE THREAD

**Issue by yathihv** [SAP/olingo-jpa-processor-v4#53]
If we see - http://services.odata.org/v4/northwind/northwind.svc/ we see the context with complete host something like m:context="http://services.odata.org/V4/Northwind/Northwind.svc/$metadata" where as our project with jpa processor generates  metadata:context="$metadata". Most of the BI tools which accepts OData won't work with the generated context but expects full URL which is the standard protocol.

**Comment by wog48** [comment]
Due to clean-up action. All issues created before 2022 get closed.

In the meantime `JPAODataServiceContext` offeres the option to set `useAbsoluteContextURL`.
