### ISSUE TITLE
Productive usage

### ISSUE THREAD

**Issue by alexanderparr** [SAP/olingo-jpa-processor-v4#54]
Hi everyone,
are there any plans to do a maven release build for productive usage? I like to create a new SAP Cloud Platform App using this framework to generate an OData Service based on our JPA Model. The OData Service shall be consumed by SAP Fiori / UI5.

Thanks in advance,
Alex

**Comment by wzagrajcz** [comment]
Hello,
Is there any update on that issue?

Thanks

**Comment by wog48** [comment]
Due to clean-up action. All issues created before 2022 get closed.
Making the framework available on maven is still work in progress.
