### ISSUE TITLE
Group by

### ISSUE THREAD

**Issue by chentopf** [SAP/olingo-jpa-processor-v4#55]
Hi 
does olingo support group by? 
Thanks

**Comment by chentopf** [comment]
I tried /OsaScans?$apply=groupby((Score), aggregate($count as total))
but got : "The URI is malformed."
Anyone familiar with groupBy in Odata?

Thanks

**Comment by wog48** [comment]
Hello,

there is no with-space allowed between COMMA and _aggregation_. So the correct string would be:

```
 /OsaScans?$apply=groupby((Score),aggregate($count as total))
```

Nevertheless, JPA Processor not supporting $apply yet.

Best regards
