### ISSUE TITLE
In param is not working in filter

### ISSUE THREAD

**Issue by nirliber** [SAP/olingo-jpa-processor-v4#56]
Hello,
When trying to filter strings according to "in (?, ?....)"
I'm getting this error:
"The types 'Edm.Boolean' and 'Edm.String' are not compatible.".

Thanks

**Comment by wog48** [comment]
Hello,

as do not know of an OData string operator _in_ is would be helpful if you can provide an OData query as an example.

**Comment by chentopf** [comment]
For example:
http://host/service/Products?$filter=Name in ('Milk', 'Cheese')

**Comment by wog48** [comment]
I will have look if what olingo provides

**Comment by wog48** [comment]
It looks like Olingo is as of now (4.5) not supporting _in_. Class `UriTokenizer` lists all the supported operation and does not contain _in_.  So `ExpressionParser` is not able to find/interpret this part and finally `FilterParser.FilterOption` throws an `UriParserSemanticException`.
As soon as the Olingo supports Odata 4.01, I can start to implement _in_ as well.

**Comment by chentopf** [comment]
Any estimations regarding Odata 4.01?

**Comment by wog48** [comment]
https://spring.io/guides/gs/accessing-data-cassandra/
