### ISSUE TITLE
Enitites filtering

### ISSUE THREAD

**Issue by Falseclock** [SAP/olingo-jpa-processor-v4#64]
Is it possible somehow filter enitites or enity fields on the fly?

want to provide or not provide some information depending on user account.

**Comment by wog48** [comment]
I guess you mean that it is possible to extend the the WHERE clause and the SELECT clause.
With the current release this is not possible.

To support instance based authorization the next version will get the option to marke attributes as protected and a mechanism to forward the user specific restrictions for those attributes. With this information the WHERE clause gets enhanced. There will be no mechanism to create a user specific projection. This is for two reasons:
* I heard this requirement only once and the solution was to have two entity types
* I have no good idea how to do that model driven

**Comment by Falseclock** [comment]
actually I want hide some sensitive information, for example passwords, price schedules, permissions and so on. 

I want setup a couple of user groups and grant them permission to access entities or fields.

**Comment by wog48** [comment]
Hello,

I have created a new version. You may want to have a look at [4-4-InstanceBasedAuthorizations]( https://github.com/SAP/olingo-jpa-processor-v4/blob/develop/jpa-tutorial/Tutorials/SpecialTopics/4-4-InstanceBasedAuthorizations.md).

**Comment by Falseclock** [comment]
Thanks @wog48 .

This is applicable for result filtering but for column filtering not.

What if add additional annotation like EdmVisibleFor 

```java
@Retention(RUNTIME)
@Target(FIELD)
public @interface EdmVisibleFor {
    /**
     * Name of the authorization claim
     *
     * @return
     */
    String name();

    /**
     * If is set to true, then column value will be set to NULL for every row in case of unsuccessful claim
     *
     * @return
     */
    Boolean setNull() default true;
  
}

```

**Comment by nico525** [comment]
I solved this by querying views, only.
These views check for  the CURRENT_USER Attribute on sql server.
My servlet changes the edm Provider datasource based on the authentication provided in the http call

**Comment by Falseclock** [comment]
@nico525 yes, you are right. This can be done by special view. 

But in some cases VIEW becomes very complicated with a lot of CASE and GROUPing. And of course this VIEW works very slow.

**Comment by nico525** [comment]
Yes, button my case the users have access to the database itself as well which is why I had to develop such a concept anyway.

**Comment by wog48** [comment]
@Falseclock I had a look at your proposal. I had something different on my mind, so lets check If I understood your requirement correctly:

_You have groups of users (I assume more than two) that shall access the same entity sets, but each group shall only have access to a subset of the properties. So the properties depend on the group a user belongs to._

Right?

**Comment by Falseclock** [comment]
@wog48 yes, exactly! )))

I have some entities with a lot of properties. Depends on user access rights I want to hide or show some of them.

For example Carfax Info:
Basic account: only common information (10 properties)
Trial account: some additional info  (15 properties)
Premium account: most information  (20 properties)
Super Premium account: full information + additional  (100+ properties)

**Comment by wog48** [comment]
@Falseclock If I got your proposal right you would add to most of the properties three `EdmVisibleFor ` annotations with different claims (or name is made a string array). If a certain claim is provided only those with `setNull = false` are taken into account, respecting $select. 

My idea was as follows:
The claims provide can be enhanced with a new interface, that provides a map that contains entity types for with a restriction shall be made and a list of properties the user is allowed to see. Later the list is intersected with `$select`, so only the allowed properties are retrieved from db.

What would you prefer?

**Comment by Falseclock** [comment]
@wog48 your variant )))

**Comment by wog48** [comment]
@Falseclock To be hounest, after rethinken both proposals, I would have prefered yours, das claims and selection restriction are Design time than.

**Comment by wog48** [comment]
@Falseclock I like to provide the following: 

A new annotation, as proposed by you, with some changes. The annotation would allow to give a list of (user) groups that are allowed to see the field, so that a field that should be accessible by __premium__ and __super premium__  just need to be annotated once. If a field has not be annotated at all it would mean that every one can see it. At this time I would skip the `setNull` and always skip the selection from the database and set OData property to null. The annotation would look as follows:

@Retention(RUNTIME)
@Target(FIELD)
public @interface EdmVisibleFor {
    /**
     * Name of the authorization claim
   */
     String[] groups();
}

Would this fulfill your needs?

**Comment by Falseclock** [comment]
@wog48 Million thanks!

That's completely fulfill our needs. )))

**Comment by wog48** [comment]
I have released the next version. Please note that it contains a bunch of additional changes. Especially the way how a servlet is implemented as been changed. Please check the new functionality to ensure that I haven't  forgot something

**Comment by wog48** [comment]
I close this, as I assume that the problem has been solved.
