### ISSUE TITLE
Custom search function

### ISSUE THREAD

**Issue by nico525** [SAP/olingo-jpa-processor-v4#68]
Hi,

Had anyone so far luck with implementing a custom query search function?
I followed the database processor example, but as soon as there is some kind of special character in the searchterm it stops working

This can be even a simple dash „-„, but the list goes on and on with other characters

**Comment by wog48** [comment]
Can you provide more details about the error you get?

**Comment by wog48** [comment]
Any update?

**Comment by wog48** [comment]
Due to clean-up action. All issues created before 2022 get closed.
