### ISSUE TITLE
JPAODataClaimsProvider is not supporting count entities queries

### ISSUE THREAD

**Issue by taj499** [SAP/olingo-jpa-processor-v4#69]
Hi,

I am exploring JPA processor api. I found that JPAODataClaimsProvider is not supporting count entities query. i checked the code. here, purposefully you are not passing  JPAODataClaimsProvider to JPAJoinQuery. Any issue with that?

Thanks

**Comment by wog48** [comment]
I had a look at the code.  `JPACountRequestProcessor` does not forward the claims when it creates an instance of `JPAJoinQuery`, method ` countEntities`.

If my first analysis is correct the problem only occurs in case you make a queries like
`.../<EntitySet>/$count `. In case you make inline count so a query like `.../<EntitySet>?$count=true` the claims should be taken into account.

**Comment by taj499** [comment]
Thanks for reply.

I actually tried it with .../<EntitySet>?$count=true and it is not working.
In one of the JPAJoinQuery constructor, it has below given code which is the issue.
this.claimsProvider = Optional.empty();

I hope, it will help you.

**Comment by wog48** [comment]
Thanks for the check. This Indicates that more tests are missing than I have expected. I will work on that issue as soon as I have finished the one I'm currently working on

**Comment by wog48** [comment]
@taj499  Have had a look at the latest version? It should solve the problem.

**Comment by taj499** [comment]
it looks good. now, 
issue Fixed.
