### ISSUE TITLE
a jpa structure is not available.

### ISSUE THREAD

**Issue by xiba3x** [SAP/olingo-jpa-processor-v4#70]
i am newbie,i followed the step as https://github.com/SAP/olingo-jpa-processor-v4/blob/develop/jpa-tutorial/Tutorials/Introduction/Introduction.md instruction,but there is a error complained "<dependency>
			<groupId>com.sap.olingo</groupId>
			<artifactId>odata-jpa-metadata</artifactId>
			<version>_current version</version>"  
a jpa structure is not available.

**Comment by wog48** [comment]
Have you cloned this repository? As of now the repo is not available via maven central

**Comment by wog48** [comment]
Due to clean-up action. All issues created before 2022 get closed.
