### ISSUE TITLE
Does olingo-jpa-processor-v4 supports “deep update”  functionality?

### ISSUE THREAD

**Issue by taj499** [SAP/olingo-jpa-processor-v4#82]
Does olingo-jpa-processor-v4 supports “deep update functionality? payload of the update can contain nested entities for creating new or updating existing related entities.

I can see example “deep insert” only. 
If it supports “deep update” then please provide me example to implement it.

**Comment by wog48** [comment]
Deep Update is a 4.01 functionality ([New: Deep Update](https://docs.oasis-open.org/odata/new-in-odata/v4.01/cn03/new-in-odata-v4.01-cn03.html#_Toc14438823)). Up to now only 4.00 is supported by the JPA Processor.

**Comment by taj499** [comment]
Thanks for reply.
Could you please let me know when do I expect it (“Deep Update”) in olingo-jpa-processor-v4 API?

**Comment by wog48** [comment]
I just played around and found out that, even so Deep Update is a 4.01 functionality, you can use it already. As of now you have to send it as 4.00 request. The data are provided in the same way as they are provided for Deep Insert. You have to implement the you implementation of JPACUDRequestHandler accordingly. Unfortunately the response is not correct. 

In case you followed the tutorial you can take the payload of the deep insert request and e.g. create a PATCH request with the following url .../AdministrativeDivisions(DivisionCode='DE5',CodeID='NUTS1',CodePublisher='Eurostat')

**Comment by wog48** [comment]
I hope this helped. In case you have another question please open a  new issue.
