### ISSUE TITLE
Collections overload DB with useless query and finally throw OutOfMemoryError

### ISSUE THREAD

**Issue by Falseclock** [SAP/olingo-jpa-processor-v4#83]
It looks like EDM provider ignores constraints and fetch type

If you try to expand this collection https://github.com/SAP/olingo-jpa-processor-v4/blob/b24005815e1a58336342dc17698300b0e2c3f959/jpa/odata-jpa-test/src/main/java/com/sap/olingo/jpa/processor/core/testmodel/BusinessPartner.java#L126

`BusinessPartner?$expand=BusinessPartnerRole&$format=json&$top=1`

then all available records from BusinessPartnerRole will be fetched, and then filtered "manually"

If query like `BusinessPartner(1)?$expand=BusinessPartnerRole&$format=json`

then only necessary records with join will be fetched.

Is there any way to optimize entity listing with expand?

**Comment by wog48** [comment]
Currently for expand JOIN-queries are generated this need to be replaced by a Subselect, which would  allows the forwarding of $top and $skip.

Originally the late filtering was created for $top and $skip on the level of the expanded entity type (so BusinessPartnerRole), which can not be realized with JPA criteria queries as it would require ROW_NUMBER( ) and ROW_NUMBER( ) is not supported by all DBs.

**Comment by wog48** [comment]
Sorry for closing, I pressed the wrong button.
I revisited that my code, actually the JPA criteria builder does not support LIMIT and OFFSET on sub-query level. Some investigations needed

**Comment by Falseclock** [comment]
@wog48 

yeah... also investigating the code

looking now at

```
    // x/a?$expand=b/c($expand=d,e/f)&$filter=...&$top=3&$orderBy=...
    // For performance reasons the expand query should only return results for the results of the higher-level query.
    // The solution for restrictions like a given key or a given filter condition, as it can be propagated to a
    // sub-query.
```

What if not use top query as sub-query for expands, but use WHERE IN () ?

If I would like to expand all entity navigations with skip, top, where, filter and orderBy, the same subquery will overload database

**Comment by wog48** [comment]
I guess you propose to use WHERE IN () containing the list of keys from the "root", so something like SELECT * FROM BusinessPartnerRole WHERE BusinessPartnerId IN ('1', '2'). Actually I wanted to prevent this, as it has some drawbacks:
1.  It requires the extraction of the retrieved keys
2.  Not all databases accept an arbitrary length of the WHERE clause, so the list of keys potentially has to be spitted and the results need to be combined

Nevertheless this seems to be the best intermediate solution. Unfortunately I was only able to create such queries for relations based on simple keys. In case of embedded ids EclipseLink  generates a malformed SQL. E.g. ...WHERE ((NULL, NULL, NULL, NULL) IN (('USA', '3166-1', 'ISO', 'en')))

On a long term I do not see another solution than switching to native queries.

**Comment by Falseclock** [comment]
by the way... it happens also for ElementCollection

```java
	@ElementCollection(fetch = FetchType.EAGER)
	@CollectionTable(schema = "odata", name = "tender_lot_attributes", joinColumns = @JoinColumn(name = "tender_lot_id"))
	private Collection<TenderLotAttribute> tenderLotAttributes;
```

**Comment by Falseclock** [comment]
@wog48 it looks like you JPA provider does not understant collections without SQL join

```java
	@ElementCollection
	private Collection<String> tenderLotAttributes = new ArrayList<String>(Arrays.asList("1111", "2222", "3333"));
```

getting

```json
{
"error": {
"code": null,
"message": "OData Library: An exception without message text was thrown."
}
}
```

**Comment by Falseclock** [comment]
@wog48 want to optimize thid bug with predefined SQL view which fetches all joins with json aggregation, but does not work because of previous comment

Entity class
```java
	@Column(name = "tender_lot_attributes")
	@ElementCollection
	@Convert(converter = TenderLotAttributeConverter.class)
	private Collection<String> tenderLotAttributes;
```

Convertor class

```java
@Converter
public class TenderLotAttributeConverter implements AttributeConverter<List<String>, String> {
	
	@Override
	public String convertToDatabaseColumn(List<String> lotAttributeList) {
		return "convertToDatabaseColumn";
	}
	
	@Override
	public List<String> convertToEntityAttribute(String jsonString) {
		return new ArrayList<String>(Arrays.asList("1111","2222","3333"));
	}
}
```

**Comment by wog48** [comment]
Please try latest release [0.3.7-a](https://github.com/SAP/olingo-jpa-processor-v4/releases/tag/0.3.7-a). This reduces the number of combinations that causes an OUT_OF_MEMORY. 
The final solution is, as mentioned, to use native queries. 

For a follow-up I have created [issues 97](https://github.com/SAP/olingo-jpa-processor-v4/issues/97 )

**Comment by DimitarPetrov** [comment]
Hello @Falseclock @wog48 ,

We have similar issue with poor performance due to inefficient queries - https://github.com/SAP/olingo-jpa-processor-v4/issues/154

Have you found any workarounds until NativeQueries are used and IN subquery is introduced.

Regards,
Dimitar
