### ISSUE TITLE
Qualifier attribute of @EdmAnnotation can't be nullable

### ISSUE THREAD

**Issue by mpbiz** [SAP/olingo-jpa-processor-v4#85]
There is no way to remove the qualifier attribute from @EdmAnnotation, since the field has a default value = "".
Finally $metadata document has empty Qualifier attribute 

Java
```Java
@EdmAnnotation(term = "Core.Description", constantExpression = @EdmAnnotation.ConstantExpression(type = CsdlConstantExpression.ConstantExpressionType.String,
            value = "Some text"))
```

XML
```xml
<Annotation Term = "Core.Description" Qualifier = "">
    <String>
       some text
    </String>
</Annotation>
```

**Comment by mpbiz** [comment]
@wog48 , updated topic with an examle

```Java
@EdmAnnotation(term = "Core.Description", constantExpression = @EdmAnnotation.ConstantExpression(type = CsdlConstantExpression.ConstantExpressionType.String,
            value = "Идентификатор категории, уникальный, серийный"))
```

> There is no way to remove the qualifier attribute from @EdmAnnotation, since the field has a default value = "".
> 
> Finally $metadata document has empty Qualifier attribute
> 
> ```
> <Annotation Term = "Core.Description" Qualifier = "">
>     <String>
>        some text
>     </String>
> </Annotation>
> ```

**Comment by mpbiz** [comment]
@wog48 , updated topic with an examle

Java
```java
@EdmAnnotation(term = "Core.Description", constantExpression = @EdmAnnotation.ConstantExpression(type = CsdlConstantExpression.ConstantExpressionType.String,
            value = "some text"))
```java

**Comment by wog48** [comment]
Please check release 0.3.5. The problem should be solved there.
