### ISSUE TITLE
Why first character of any properties in CSDL and service documents converted to uppercase

### ISSUE THREAD

**Issue by Falseclock** [SAP/olingo-jpa-processor-v4#86]
All entity properties declared with lower case for first character .

Is there any option to disable case convertion?

**Comment by wog48** [comment]
This is the convention used by the Olingo V2 JPA Processor. 
As of now the only way to overrule this convention is provide a subclass of `JPAEdmMetadataPostProcessor`, which is originally foreseen to handle exceptional cases. An instance can be provided to the session context. The class has a method `processProperty`, which allows e.g. to change the external name.

**Comment by Falseclock** [comment]
@wog48 perfect! Thanks for the hint

```java
    @Override
    public void processProperty(IntermediatePropertyAccess property, String jpaManagedTypeClassName) {

        char[] c = property.getInternalName().toCharArray();
        c[0] = Character.toLowerCase(c[0]);

        property.setExternalName(new String(c));
    }
```

**Comment by spalanca** [comment]
It would be possible to do the same action in the oData v2?
