### ISSUE TITLE
Make JPAODataServiceContext not final?

### ISSUE THREAD

**Issue by Falseclock** [SAP/olingo-jpa-processor-v4#87]
https://github.com/SAP/olingo-jpa-processor-v4/blob/fbbca219db0386d1480102982abdd2b0bc95b93d/jpa/odata-jpa-processor/src/main/java/com/sap/olingo/jpa/processor/core/api/JPAODataServiceContext.java#L34

If it wold be extendable, then can be used with Spring Boot

**Comment by wog48** [comment]
As of now I had had a problem crating spring boot based services. I will provide an tutorial.

**Comment by Falseclock** [comment]
Yes, it is possible now, but JPA DataServiceContext does not allow to create own instance of EntityManagerFactory which enforces to describe persistance in xml file.

look at this commit https://github.com/Falseclock/olingo-jpa-processor-v4/commit/57988d828668c3ae31d805afad399f7f08b47ba8

**Comment by wog48** [comment]
That's exactly an enhancement that shall be provided with the next version.

**Comment by wog48** [comment]
With release 0.3.5 you can also create an own [Name Builder](https://github.com/SAP/olingo-jpa-processor-v4/blob/develop/jpa/odata-jpa-metadata/src/main/java/com/sap/olingo/jpa/metadata/core/edm/mapper/api/JPAEdmNameBuilder.java) and provided it via the session context.
