### ISSUE TITLE
Trouble with composite key where one part references an Entity

### ISSUE THREAD

**Issue by ericraskin** [SAP/olingo-jpa-processor-v4#9]
I am trying to set up a pretty simple relationship:

Donor - primary key ID (field name is ID in the table)

Donation - primary key is composite:
    Donor ID (references donor - field name is DON_DON_ID in the table)
    Transaction ID (makes the key unique - field name is TRANID in the table)

Here are my definitions:
``
     public class DonationId implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	@Column(name="DON_DON_ID")
	private long donor;
	
	@Column(name="TRANID")
	private long tranId;
	...
    }
    
    @Entity(name="Donor")
    @Table(schema="GEBOWNER", name="DONORS")
    public class Donor {

	@Id
	@Column(name="ID")
	private Long id;

	@OneToMany(mappedBy="donor", fetch=FetchType.LAZY)
	private Collection<Donation> donations;
       ...
    }
      
    @Entity(name="Donation")
    @IdClass(DonationId.class)
    @Table(schema="GEBOWNER", name="VW_DONTRANS")
    public class Donation {

		@Id
		private long tranId;

		@ManyToOne
		@Id
		private Donor donor;	
        ...
    }
``

The Metadata I get is this:
![image](https://user-images.githubusercontent.com/6988904/31959850-e4d196f2-b8c3-11e7-8168-5ad36b373938.png)

Look at the Key under  Donation entity.  It only shows TranID and does not show the Donor.  Shouldn't it, since it is part of the Donation table key?

What am I doing wrong - or is something wrong with the metadata loader?  What is the best way to debug this?

**Comment by wog48** [comment]
Currently the JPA Processor does not support using an association as a key:
```
	@ManyToOne
	@Id
	private Donor donor;
```
As short workaround the Id and the association can be split: 

```
  @Id
  private long donor;

  @ManyToOne
  private Donor relatedDonor;
```
which would result in the following metadata:

```
<EntityType Name="Donation">
    <Key>
        <PropertyRef Name="TranId"/>
        <PropertyRef Name="Donor"/>
    </Key>
    <Property Name="TranId" Type="Edm.Int64"/>
    <Property Name="Donor" Type="Edm.Int64"/>
    <NavigationProperty Name="RelatedDonor" Type="Issue.Donor" Partner="Donations"/>
</EntityType>
```

Additional clarification is needed on this topic, e.g. is it allowed that a property and a navigation property have the same name.

**Comment by ericraskin** [comment]
OK, thank you.  I will try it and see what happens.  

---------------------------------------------------------------------------------------------------------------------------------------------

Eric H. Raskin                                                                                                      914-765-0500 x120

Professional Advertising Systems Inc.                                                                 914-765-0503 fax

200 Business Park Drive Suite 304                                                                     eraskin@paslists.com

Armonk, NY 10504                                                                                              http://www.paslists.com





-----Original message-----

**Comment by ericraskin** [comment]
Thanks.  Will open a new issue for the next problem. :-)
