### ISSUE TITLE
Byte Array to String Conversion

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [SAP/olingo-jpa-processor-v4#90]
https://github.com/SAP/olingo-jpa-processor-v4/blob/66b898acb057f1d8c45947331d1d5a066d03477b/jpa/odata-jpa-metadata/src/main/java/com/sap/olingo/jpa/metadata/core/edm/mapper/annotation/SchemaReader.java#L43

Converting data from byte arrays to String may result in data loss if no encoding is specified.

**Comment by wog48** [comment]
Thanks for supporting. 

This will be changed with the next release.
