### ISSUE TITLE
Code Correctness: Erroneous String Compare

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [SAP/olingo-jpa-processor-v4#93]
https://github.com/SAP/olingo-jpa-processor-v4/blob/bc0c49d89cb49367554c89ed26a46cbe748e7243/jpa/odata-jpa-processor/src/main/java/com/sap/olingo/jpa/processor/core/converter/JPAStructuredResultConverter.java#L60
Strings should be compared with the equals() method, not == or !=.

**Comment by wog48** [comment]
Thanks for supporting,

this will be corrected with the next release.
