### ISSUE TITLE
Support new date time API

### ISSUE THREAD

**Issue by SeriousSoftware** [SAP/olingo-jpa-processor-v4#99]
com.sap.olingo.jpa.metadata.core.edm.mapper.exception.ODataJPAModelException: Type 'java.time.ZonedDateTime' of attribute 'at' is not supported. Mapping not possible. 

Take note of [Olingo merge](https://github.com/apache/olingo-odata4/pull/57).

**Comment by wog48** [comment]
Hello,

the corresponding adoptions can be found in branch [release-0.3.8](https://github.com/SAP/olingo-jpa-processor-v4/tree/feature/release-0.3.8)
